feat(post-checkout): don't run get-mathlib-cache if in mathlib

diff --git a/mathlibtools/post-checkout b/mathlibtools/post-checkout
--- a/mathlibtools/post-checkout
+++ b/mathlibtools/post-checkout
@@ -8,12 +8,16 @@ NEW_HEAD=$2
 CHANGED_BRANCH=$3
 
 if [ "$CHANGED_BRANCH" -eq "1" ]; then
-    if /usr/bin/env python3 -c ""; then
+	if /usr/bin/env python3 -c ""; then
 		echo "Trying to fetch cached olean"
 		leanproject get-cache
-		leanproject get-mathlib-cache
+		# If the current project is not called "mathlib", then get a mathlib cache.
+		leanpkg dump | grep --quiet 'name = "mathlib"'
+		if [ $? -ne 0 ]; then
+			leanproject get-mathlib-cache
+		fi
 		leanproject delete-zombies
-    else
-        echo "'env python3' failed; not running post-checkout hook"
-    fi
+	else
+		echo "'env python3' failed; not running post-checkout hook"
+	fi
 fi
